baseURL: https://grpc.io/
disableKinds: [taxonomy, term]
googleAnalytics: G-8H17ZWYV40

theme: [docsy]

defaultContentLanguageInSubdir: false

languages:
  en:
    title: gRPC
    description: A high-performance, open source universal RPC framework
    contentDir: content/en
    languageName: English
    languageCode: en-us

enableGitInfo: true
enableRobotsTXT: true

params:
  gtmID: "GTM-55D2HXLW"
  copyright: gRPC Authors
  repo: &repo https://github.com/grpc/grpc.io
  github_repo: *repo
  github_project_repo: *repo
  github_branch: main
  branch: main
  locale: en_US
  grpc_vers:
    core: v1.66.0
    go: v1.71.0
    java: v1.70.0
    node: "@grpc/grpc-js@1.9.0"
  font_awesome_version: 5.12.1
  gcs_engine_id: 788f3b1ec3a111a2f
  ui:
    footer_about_disable: true
    navbar_logo: true
    navbar_translucent_over_cover_disable: true
    sidebar_menu_compact: true

  show_banner: false

  fonts:
    - name: Open Sans
      sizes: [300, 400, 600, 700]
      type: sans_serif

  logos:
    navbar: grpc-horizontal-white.png
    hero: grpc-logo.png
    footer: grpc-horizontal-white.png

  links:
    user:
      - name: Twitter
        url: https://twitter.com/grpcio
        icon: fab fa-twitter
      - name: Google Groups
        url: https://groups.google.com/g/grpc-io
        icon: fab fa-google
      - name: Gitter
        url: https://gitter.im/grpc/grpc
        icon: fab fa-gitter
      - name: YouTube
        url: https://www.youtube.com/@grpcio
        icon: fab fa-youtube
    developer:
      - name: GitHub
        url: https://github.com/grpc
        icon: fab fa-github

  mermaid:
    enable: true
    theme: "neutral"

markup:
  goldmark:
    renderer: {unsafe: true}
  highlight:
    style: manni
  tableOfContents:
    startLevel: 2
    endLevel: 5
    ordered: false

# Netlify _redirects file

mediaTypes:
  text/netlify: {}

outputFormats:
  REDIRECTS:
    mediaType: text/netlify
    baseName: _redirects
    notAlternative: true

outputs:
  home: [HTML, REDIRECTS, RSS]
