baseURL: https://grpc.io/
languageCode: en-us
title: gRPC
disableKinds: [taxonomy, taxonomyTerm]
pygmentsCodeFences: true

theme: ['docsy']

enableGitInfo: true

params:
  copyright: 'The Linux Foundation'
  repo: &repo 'https://github.com/grpc/grpc.io'
  github_repo: *repo
  github_project_repo: *repo
  branch: main
  locale: en_US
  grpc_vers:
    core: v1.34.0
    go: v1.34.0
    java: v1.34.1
  font_awesome_version: 5.12.1
  description: A high-performance, open source universal RPC framework
  ui:
    sidebar_menu_compact: true
    navbar_logo: true

    # If Algolia DocSearch is enabled, sidebar search is not supported
    sidebar_search_disable: false

    # Adds a reading time to the top of each doc.
    # If you want this feature, but occasionally need to remove the Reading time from a single page,
    # add "hide_readingtime: true" to the page's front matter
    readingtime:
      enable: false

  show_banner: false

  social:
    gitter: https://gitter.im/grpc/grpc
    reddit: https://www.reddit.com/r/grpc
    twitter: https://twitter.com/grpcio
    twitter_handle: '@grpcio'

  features:
    - title: Simple service definition
      description: Define your service using Protocol Buffers, a powerful binary serialization toolset and language
      icon: feature-1.svg
    - title: Start quickly and scale
      description: Install runtime and dev environments with a single line and also scale to millions of RPCs per second with the framework
      icon: feature-2.svg
    - title: Works across languages and platforms
      description: Automatically generate idiomatic client and server stubs for your service in a variety of languages and platforms
      icon: feature-3.svg
    - title: Bi-directional streaming and integrated auth
      description: Bi-directional streaming and fully integrated pluggable authentication with HTTP/2-based transport
      icon: feature-4.svg

  fonts:
    - name: 'Open Sans'
      sizes: [300, 400, 600, 700]
      type: sans_serif

  logos:
    navbar: grpc-horizontal-white.png
    hero: grpc-logo.png
    footer: grpc-horizontal-white.png

  links:
    user:
      - name: 'Twitter'
        url: 'https://twitter.com/grpcio'
        icon: 'fab fa-twitter'
        desc: 'Follow us on Twitter!'
      - name: 'Google Groups'
        url: 'https://groups.google.com/g/grpc-io'
        icon: 'fab fa-google'
        desc: 'Join our Google community'
    developer:
      - name: 'GitHub'
        url: 'https://github.com/grpc'
        icon: 'fab fa-github'
        desc: 'Development takes place here!'
      - name: 'Gitter'
        url: https://gitter.im/grpc/grpc
        icon: 'fab fa-gitter'
        desc: 'Where developers come to talk'

  # Google Custom Search Engine ID. Remove or comment out to disable search.
  gcs_engine_id: '788f3b1ec3a111a2f'

  # Enable Algolia DocSearch
  algolia_docsearch: false

  #Enable offline search with Lunr.js
  offlineSearch: false

markup:
  goldmark:
    renderer: {unsafe: true}
  highlight:
    style: manni
  tableOfContents:
    startLevel: 2
    endLevel: 5
    ordered: false

# Configuration required for auto-generating the Netlify _redirects file
mediaTypes:
  text/netlify:
    delimiter: ''

outputFormats:
  REDIRECTS:
    mediaType: text/netlify
    baseName: _redirects
  RSS:
    baseName: feed

outputs:
  home: [HTML, REDIRECTS, RSS]

# Site menus

menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Docs
      url: /docs/
      identifier: docs
      weight: 2
    - name: Showcase
      url: /showcase/
      weight: 3
    - name: Blog
      url: /blog/
      weight: 4
    - name: Community
      url: /community/
      weight: 5
    - name: Overview
      url: /docs/
      weight: 1
      parent: docs
    - name: What is gRPC?
      url: /docs/what-is-grpc/
      weight: 1
      parent: docs
    - name: Languages
      url: /docs/languages/
      weight: 2
      parent: docs
    - name: Platforms
      url: /docs/platforms/
      weight: 2
      parent: docs
    - name: Guides
      url: /docs/guides/
      identifier: guides
      weight: 4
      parent: docs
    - name: FAQ
      url: /faq/
      weight: 7
      parent: docs
